### ISSUE TITLE
Caminho das imagens de Screenshot

### ISSUE THREAD

**Issue by janynnegomes** [joelgarciajr84/wp-animal-ong#1]
O caminho das imagens de print das telas, exibidas no arquivo **README.md** está com erro 403, acesso negado.

Exemplo: https://lh6.googleusercontent.com/TjEOXklrOO-QJRsOdJfJH9WrFf12Q8BbzV7ysJuflVdvatr14ljV8VDiqmnK-2d703v2ZiMMWv8=w1831-h995

**Comment by joelgarciajr84** [comment]
Ja vou corrigir

**Comment by joelgarciajr84** [comment]
@devnetgomez caminho das imagens corrigido, novas imagens inseridas
